#!/bin/bash
set -e  # Exit immediately if a command exits with a non-zero status
export DEBIAN_FRONTEND=noninteractive

echo "[INFO] Updating APT package list..."
apt-get update

echo "[INFO] Installing jq and msmtp"
apt-get install -y jq  msmtp
apt install -y msmtp

echo "[INFO] Reloading systemd daemon..."
systemctl daemon-reload

echo "[INFO] Enabling services..."
systemctl enable houston-dbus.service || true
sudo systemctl enable --now houstonzfs-storage-alert.timer || true
systemctl enable houstonzfs-storage-alert.service || true


echo "[INFO] Starting services..."
systemctl start houston-dbus.service || true
systemctl restart zed || true

echo "[✅ SUCCESS] jq installed and services started!"


echo "[INFO] Installing Python dependencies..."
pip3 install --upgrade pip
pip3 install --upgrade google-auth google-auth-oauthlib