#!/bin/bash
set -e
export DEBIAN_FRONTEND=noninteractive

echo "[INFO] Reloading systemd daemon..."
systemctl daemon-reload

echo "[INFO] Enabling services..."
systemctl enable houston-dbus.service || true
systemctl enable --now houstonzfs-storage-alert.timer || true
systemctl enable houstonzfs-storage-alert.service || true

echo "[INFO] Starting services..."
systemctl restart zed || true
systemctl restart houston-dbus.service || true

echo "[INFO] Installing Python dependencies..."
pip3 install --upgrade pip
pip3 install --upgrade google-auth google-auth-oauthlib

echo "[SUCCESS] Services started and Python packages installed!"
